### ISSUE TITLE
"FIle to patch: " option. Does this mean fail? 

### ISSUE THREAD

**Issue by elvis6535** [SolidHal/icecat-arm#2]
After I attempted to run "sudo ./crossBuildIcecatArm.sh" my LinuxOS reported

"E: There were unauthenticated packages and -y was used without --allow-unauthenticated
Reading package lists... Done
E: You must put some 'source' URIs in your sources.list
./nativeBuildIcecat.sh: 21: ./nativeBuildIcecat.sh: wget: not found
tar (child): icecat-52.6.0-gnu1.tar.bz2: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
/bin/tar: Child returned status 2
/bin/tar: Error is not recoverable: exiting now
/bin/cp: cannot create regular file 'icecat-52.6.0/mozconfig': No such file or directory
./nativeBuildIcecat.sh: 27: cd: can't cd to icecat-52.6.0/
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/build/moz.configure/toolchain.configure b/build/moz.configure/toolchain.configure
|index 15bc045..9d7bef5 100644
|--- a/build/moz.configure/toolchain.configure
|+++ b/build/moz.configure/toolchain.configure
--------------------------
File to patch: 
[2]+  Stopped                 sudo ./crossBuildIcecatArm.sh"

what issue does this imply?

**Comment by SolidEva** [comment]
```
wget: not found
```
This would be your main problem, grab wget with `sudo apt install wget`. I'll add that to the dependencies. 
The rest looks like failues due to the source not being available, since you didn't have wget installed to download it. 

I also see `E: You must put some 'source' URIs in your sources.list` which will cause some problems. Is this a debian install, or are you using a different distro?
If youre using debian, you should have source apt repos in your sources.list, if not you'll have to see if your distro has source apt repos. 
Since this was only done on debian, I can't say that it will go smoothly on other distros. 

I hope that helps!

EDIT: For the future, if you paste your logs between two sets of ``` it won't get weird formatting. :)

**Comment by elvis6535** [comment]
Unfortunately, 
Ive tried that before but the apt function is also not installed. 
"root@imx6ull14x14evk:~# sudo apt install wget
sudo: apt: command not found"

**Comment by SolidEva** [comment]
Then I don’t think you’re on a Debian or Debian related distro. I doubt these scripts will work for you, as they modify the Debian package source files. 
You’ll have to see if your distro packages icecat.
